package org.fujure.fbc.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class TypeSpecifier extends TypeSpec {
  public final ListTypeSpecFragm listtypespecfragm_;
  public TypeSpecifier(ListTypeSpecFragm p1) { listtypespecfragm_ = p1; }

  public <R,A> R accept(org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpec.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpecifier) {
      org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpecifier x = (org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpecifier)o;
      return this.listtypespecfragm_.equals(x.listtypespecfragm_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtypespecfragm_.hashCode();
  }


}
