# OracleJDK8 no longer installs on Xenial, which is the default
dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true # nothing to do for install
script:
  - ./gradlew build publish && cd src/test/e2e-test-gradle && ../../../gradlew build
