package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class AbstractTypelessFuncDecl  extends FuncDecl {
  public final String jid_;
  public final ListParam listparam_;
  public AbstractTypelessFuncDecl(String p1, ListParam p2) { jid_ = p1; listparam_ = p2; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FuncDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.AbstractTypelessFuncDecl) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.AbstractTypelessFuncDecl x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.AbstractTypelessFuncDecl)o;
      return this.jid_.equals(x.jid_) && this.listparam_.equals(x.listparam_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.jid_.hashCode())+this.listparam_.hashCode();
  }


}
