package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class CharLiteral  extends Literal {
  public final String jchar_;
  public CharLiteral(String p1) { jchar_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.CharLiteral) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.CharLiteral x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.CharLiteral)o;
      return this.jchar_.equals(x.jchar_);
    }
    return false;
  }

  public int hashCode() {
    return this.jchar_.hashCode();
  }


}
