package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class ComplexRefExpr  extends Expr {
  public final String jid_1, jid_2;
  public ComplexRefExpr(String p1, String p2) { jid_1 = p1; jid_2 = p2; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ComplexRefExpr) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ComplexRefExpr x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ComplexRefExpr)o;
      return this.jid_1.equals(x.jid_1) && this.jid_2.equals(x.jid_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.jid_1.hashCode())+this.jid_2.hashCode();
  }


}
