package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class ConcreteTypelessFuncDecl extends FuncDecl {
  public final String jid_;
  public final ListParam listparam_;
  public final Expr expr_;
  public ConcreteTypelessFuncDecl(String p1, ListParam p2, Expr p3) { jid_ = p1; listparam_ = p2; expr_ = p3; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FuncDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ConcreteTypelessFuncDecl) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ConcreteTypelessFuncDecl x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ConcreteTypelessFuncDecl)o;
      return this.jid_.equals(x.jid_) && this.listparam_.equals(x.listparam_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.jid_.hashCode())+this.listparam_.hashCode())+this.expr_.hashCode();
  }


}
