package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class ConcreteTypedFuncDecl  extends FuncDecl {
  public final String jid_;
  public final ListParam listparam_;
  public final TypeDesc typedesc_;
  public final Expr expr_;
  public ConcreteTypedFuncDecl(String p1, ListParam p2, TypeDesc p3, Expr p4) { jid_ = p1; listparam_ = p2; typedesc_ = p3; expr_ = p4; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FuncDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ConcreteTypedFuncDecl) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ConcreteTypedFuncDecl x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ConcreteTypedFuncDecl)o;
      return this.jid_.equals(x.jid_) && this.listparam_.equals(x.listparam_) && this.typedesc_.equals(x.typedesc_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.jid_.hashCode())+this.listparam_.hashCode())+this.typedesc_.hashCode())+this.expr_.hashCode();
  }


}
