package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public abstract class Def implements java.io.Serializable {
  public abstract <R,A> R accept(Def.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.SimpleValueDef p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FunctionValueDef p, A arg);

  }

}
