package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class ExprCallArg extends CallArg {
  public final Expr expr_;
  public ExprCallArg(Expr p1) { expr_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.CallArg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ExprCallArg) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ExprCallArg x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ExprCallArg)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
