package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class FileInNamedPackage  extends FileContents {
  public final PkgName pkgname_;
  public final Imports imports_;
  public final Defs defs_;
  public FileInNamedPackage(PkgName p1, Imports p2, Defs p3) { pkgname_ = p1; imports_ = p2; defs_ = p3; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FileContents.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FileInNamedPackage) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FileInNamedPackage x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FileInNamedPackage)o;
      return this.pkgname_.equals(x.pkgname_) && this.imports_.equals(x.imports_) && this.defs_.equals(x.defs_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.pkgname_.hashCode())+this.imports_.hashCode())+this.defs_.hashCode();
  }


}
