package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public abstract class FileContents implements java.io.Serializable {
  public abstract <R,A> R accept(FileContents.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FileInNamedPackage p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FileInDefaultPackage p, A arg);

  }

}
