package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class FullBinding  extends Binding {
  public final String jid_;
  public final TypeDesc typedesc_;
  public final Expr expr_;
  public FullBinding(String p1, TypeDesc p2, Expr p3) { jid_ = p1; typedesc_ = p2; expr_ = p3; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Binding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FullBinding) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FullBinding x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FullBinding)o;
      return this.jid_.equals(x.jid_) && this.typedesc_.equals(x.typedesc_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.jid_.hashCode())+this.typedesc_.hashCode())+this.expr_.hashCode();
  }


}
