package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class FunCallExpr extends Expr {
  public final String jid_;
  public final ListCallArg listcallarg_;
  public FunCallExpr(String p1, ListCallArg p2) { jid_ = p1; listcallarg_ = p2; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FunCallExpr) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FunCallExpr x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FunCallExpr)o;
      return this.jid_.equals(x.jid_) && this.listcallarg_.equals(x.listcallarg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.jid_.hashCode())+this.listcallarg_.hashCode();
  }


}
