package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class FunctionValueDef extends Def {
  public final FuncDecl funcdecl_;
  public FunctionValueDef(FuncDecl p1) { funcdecl_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FunctionValueDef) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FunctionValueDef x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FunctionValueDef)o;
      return this.funcdecl_.equals(x.funcdecl_);
    }
    return false;
  }

  public int hashCode() {
    return this.funcdecl_.hashCode();
  }


}
