package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public abstract class FuncType implements java.io.Serializable {
  public abstract <R,A> R accept(FuncType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ZeroArgFuncType p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.MultiArgFuncType p, A arg);

  }

}
