package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public abstract class FuncTypeFragm implements java.io.Serializable {
  public abstract <R,A> R accept(FuncTypeFragm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.SimpleFuncTypeFragm p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FuncFuncTypeFragm p, A arg);

  }

}
