package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class FuncTypeDesc  extends TypeDesc {
  public final FuncType functype_;
  public FuncTypeDesc(FuncType p1) { functype_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.TypeDesc.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FuncTypeDesc) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FuncTypeDesc x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.FuncTypeDesc)o;
      return this.functype_.equals(x.functype_);
    }
    return false;
  }

  public int hashCode() {
    return this.functype_.hashCode();
  }


}
