package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class GenericTypeDescValue extends GenericTypeValue {
  public final TypeDesc typedesc_;
  public GenericTypeDescValue(TypeDesc p1) { typedesc_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.GenericTypeValue.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.GenericTypeDescValue) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.GenericTypeDescValue x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.GenericTypeDescValue)o;
      return this.typedesc_.equals(x.typedesc_);
    }
    return false;
  }

  public int hashCode() {
    return this.typedesc_.hashCode();
  }


}
