package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class IdSimpleTypeFragm  extends SimpleTypeFragm {
  public final String jid_;
  public IdSimpleTypeFragm(String p1) { jid_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.SimpleTypeFragm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.IdSimpleTypeFragm) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.IdSimpleTypeFragm x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.IdSimpleTypeFragm)o;
      return this.jid_.equals(x.jid_);
    }
    return false;
  }

  public int hashCode() {
    return this.jid_.hashCode();
  }


}
