package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class ImportStmt  extends Import {
  public final ListImportFragm listimportfragm_;
  public ImportStmt(ListImportFragm p1) { listimportfragm_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Import.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ImportStmt) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ImportStmt x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ImportStmt)o;
      return this.listimportfragm_.equals(x.listimportfragm_);
    }
    return false;
  }

  public int hashCode() {
    return this.listimportfragm_.hashCode();
  }


}
