package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class ImportStmts  extends Imports {
  public final ListImport listimport_;
  public ImportStmts(ListImport p1) { listimport_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Imports.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ImportStmts) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ImportStmts x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.ImportStmts)o;
      return this.listimport_.equals(x.listimport_);
    }
    return false;
  }

  public int hashCode() {
    return this.listimport_.hashCode();
  }


}
