package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class LetDefinition extends LetDef {
  public final Binding binding_;
  public LetDefinition(Binding p1) { binding_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.LetDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.LetDefinition) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.LetDefinition x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.LetDefinition)o;
      return this.binding_.equals(x.binding_);
    }
    return false;
  }

  public int hashCode() {
    return this.binding_.hashCode();
  }


}
