package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class LetExpr extends Expr {
  public final ListLetDef listletdef_;
  public final Expr expr_;
  public LetExpr(ListLetDef p1, Expr p2) { listletdef_ = p1; expr_ = p2; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.LetExpr) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.LetExpr x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.LetExpr)o;
      return this.listletdef_.equals(x.listletdef_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listletdef_.hashCode())+this.expr_.hashCode();
  }


}
