package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public abstract class Literal implements java.io.Serializable {
  public abstract <R,A> R accept(Literal.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.IntLiteral p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.UnitLiteral p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.BoolTrueLiteral p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.BoolFalseLiteral p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.CharLiteral p, A arg);
    public R visit(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.StringLiteral p, A arg);

  }

}
