package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class MethCallExpr  extends Expr {
  public final Expr expr_;
  public final String jid_;
  public final ListCallArg listcallarg_;
  public MethCallExpr(Expr p1, String p2, ListCallArg p3) { expr_ = p1; jid_ = p2; listcallarg_ = p3; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.MethCallExpr) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.MethCallExpr x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.MethCallExpr)o;
      return this.expr_.equals(x.expr_) && this.jid_.equals(x.jid_) && this.listcallarg_.equals(x.listcallarg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.expr_.hashCode())+this.jid_.hashCode())+this.listcallarg_.hashCode();
  }


}
