package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class NameInitBinding  extends Binding {
  public final String jid_;
  public final Expr expr_;
  public NameInitBinding(String p1, Expr p2) { jid_ = p1; expr_ = p2; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Binding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.NameInitBinding) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.NameInitBinding x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.NameInitBinding)o;
      return this.jid_.equals(x.jid_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.jid_.hashCode())+this.expr_.hashCode();
  }


}
