package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class SimpleValueDef  extends Def {
  public final Binding binding_;
  public SimpleValueDef(Binding p1) { binding_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.SimpleValueDef) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.SimpleValueDef x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.SimpleValueDef)o;
      return this.binding_.equals(x.binding_);
    }
    return false;
  }

  public int hashCode() {
    return this.binding_.hashCode();
  }


}
