package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class SimpleFuncTypeFragm extends FuncTypeFragm {
  public final SimpleType simpletype_;
  public SimpleFuncTypeFragm(SimpleType p1) { simpletype_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FuncTypeFragm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.SimpleFuncTypeFragm) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.SimpleFuncTypeFragm x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.SimpleFuncTypeFragm)o;
      return this.simpletype_.equals(x.simpletype_);
    }
    return false;
  }

  public int hashCode() {
    return this.simpletype_.hashCode();
  }


}
