package org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn; // Java Package generated by the BNF Converter.

public class StmtBlockExpr  extends Expr {
  public final ListStmt liststmt_;
  public StmtBlockExpr(ListStmt p1) { liststmt_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.StmtBlockExpr) {
      org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.StmtBlockExpr x = (org.fujure.fbc.parser.bnfc.antlr.fujure.Absyn.StmtBlockExpr)o;
      return this.liststmt_.equals(x.liststmt_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststmt_.hashCode();
  }


}
