package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class StringLiteral extends Literal {
  public final String jstring_;
  public StringLiteral(String p1) { jstring_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.StringLiteral) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.StringLiteral x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.StringLiteral)o;
      return this.jstring_.equals(x.jstring_);
    }
    return false;
  }

  public int hashCode() {
    return this.jstring_.hashCode();
  }


}
