package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class ValueRefFragment extends ValRefFragm {
  public final String jid_;
  public ValueRefFragment(String p1) { jid_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ValRefFragm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ValueRefFragment) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ValueRefFragment x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ValueRefFragment)o;
      return this.jid_.equals(x.jid_);
    }
    return false;
  }

  public int hashCode() {
    return this.jid_.hashCode();
  }


}
