package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class ZeroArgFuncType extends FuncType {
  public final FuncTypeFragm functypefragm_;
  public ZeroArgFuncType(FuncTypeFragm p1) { functypefragm_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FuncType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ZeroArgFuncType) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ZeroArgFuncType x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ZeroArgFuncType)o;
      return this.functypefragm_.equals(x.functypefragm_);
    }
    return false;
  }

  public int hashCode() {
    return this.functypefragm_.hashCode();
  }


}
