package org.fujure.fbc.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class FileInDefaultPackage extends FileContents {
  public final ValDef valdef_;
  public FileInDefaultPackage(ValDef p1) { valdef_ = p1; }

  public <R,A> R accept(org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileContents.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileInDefaultPackage) {
      org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileInDefaultPackage x = (org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileInDefaultPackage)o;
      return this.valdef_.equals(x.valdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.valdef_.hashCode();
  }


}
