package org.fujure.fbc.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class FileInNamedPackage extends FileContents {
  public final ListPkgFragm listpkgfragm_;
  public final ListValDef listvaldef_;
  public FileInNamedPackage(ListPkgFragm p1, ListValDef p2) { listpkgfragm_ = p1; listvaldef_ = p2; }

  public <R,A> R accept(org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileContents.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileInNamedPackage) {
      org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileInNamedPackage x = (org.fujure.fbc.bnfc.antlr.Fujure.Absyn.FileInNamedPackage)o;
      return this.listpkgfragm_.equals(x.listpkgfragm_) && this.listvaldef_.equals(x.listvaldef_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listpkgfragm_.hashCode())+this.listvaldef_.hashCode();
  }


}
