package org.fujure.fbc.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public abstract class PkgFragm implements java.io.Serializable {
  public abstract <R,A> R accept(PkgFragm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(org.fujure.fbc.bnfc.antlr.Fujure.Absyn.PackageFragment p, A arg);

  }

}
