package org.fujure.fbc.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class TypeSpecFragment extends TypeSpecFragm {
  public final String ident_;
  public TypeSpecFragment(String p1) { ident_ = p1; }

  public <R,A> R accept(org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpecFragm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpecFragment) {
      org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpecFragment x = (org.fujure.fbc.bnfc.antlr.Fujure.Absyn.TypeSpecFragment)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
