package org.fujure.truffle;

import org.fujure.truffle.nodes.ExprNode;
import org.fujure.truffle.nodes.NegationExprNode;
import org.fujure.truffle.nodes.NegationExprNodeGen;

/*
 * This class is a workaround for the fact that you can't refer to
 * classes generated by a Java annotation processor from inside Kotlin code.
 */
public class NodesFactory {
    public static NegationExprNode createNegationExprNode(ExprNode operand) {
        return NegationExprNodeGen.create(operand);
    }
}
