package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class CharLiteral extends Literal {
  public final Character char_;
  public CharLiteral(Character p1) { char_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.CharLiteral) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.CharLiteral x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.CharLiteral)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
