package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class ExprLiteral extends Expr {
  public final Literal literal_;
  public ExprLiteral(Literal p1) { literal_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ExprLiteral) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ExprLiteral x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.ExprLiteral)o;
      return this.literal_.equals(x.literal_);
    }
    return false;
  }

  public int hashCode() {
    return this.literal_.hashCode();
  }


}
