package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class FileInNamedPackage extends FileContents {
  public final PkgName pkgname_;
  public final Defs defs_;
  public FileInNamedPackage(PkgName p1, Defs p2) { pkgname_ = p1; defs_ = p2; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FileContents.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FileInNamedPackage) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FileInNamedPackage x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.FileInNamedPackage)o;
      return this.pkgname_.equals(x.pkgname_) && this.defs_.equals(x.defs_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pkgname_.hashCode())+this.defs_.hashCode();
  }


}
