package org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn; // Java Package generated by the BNF Converter.

public class IntLiteral extends Literal {
  public final Integer integer_;
  public IntLiteral(Integer p1) { integer_ = p1; }

  public <R,A> R accept(org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.IntLiteral) {
      org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.IntLiteral x = (org.fujure.fbc.parser.bnfc.antlr.Fujure.Absyn.IntLiteral)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
